
package org.tempuri.login;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SSOUserLogin", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.16.67.8/SSOLogin/SSOUserLogin.asmx?wsdl")
public class SSOUserLogin
    extends Service
{

    private final static URL SSOUSERLOGIN_WSDL_LOCATION;
    private final static WebServiceException SSOUSERLOGIN_EXCEPTION;
    private final static QName SSOUSERLOGIN_QNAME = new QName("http://tempuri.org/", "SSOUserLogin");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.67.8/SSOLogin/SSOUserLogin.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SSOUSERLOGIN_WSDL_LOCATION = url;
        SSOUSERLOGIN_EXCEPTION = e;
    }

    public SSOUserLogin() {
        super(__getWsdlLocation(), SSOUSERLOGIN_QNAME);
    }

    public SSOUserLogin(WebServiceFeature... features) {
        super(__getWsdlLocation(), SSOUSERLOGIN_QNAME, features);
    }

    public SSOUserLogin(URL wsdlLocation) {
        super(wsdlLocation, SSOUSERLOGIN_QNAME);
    }

    public SSOUserLogin(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SSOUSERLOGIN_QNAME, features);
    }

    public SSOUserLogin(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SSOUserLogin(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SSOUserLoginSoap
     */
    @WebEndpoint(name = "SSOUserLoginSoap")
    public SSOUserLoginSoap getSSOUserLoginSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SSOUserLoginSoap"), SSOUserLoginSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SSOUserLoginSoap
     */
    @WebEndpoint(name = "SSOUserLoginSoap")
    public SSOUserLoginSoap getSSOUserLoginSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SSOUserLoginSoap"), SSOUserLoginSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SSOUSERLOGIN_EXCEPTION!= null) {
            throw SSOUSERLOGIN_EXCEPTION;
        }
        return SSOUSERLOGIN_WSDL_LOCATION;
    }

}
