
package org.tempuri.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SSOUserLoginSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SSOUserLoginSoap {


    /**
     * ��ȡ��¼�û����û����������:һ��GUID�ַ���������:�ַ����ͣ���¼�û����û��������ؿ�ֵ��""���û������
     * 
     * @param guid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SSOLogin", action = "http://tempuri.org/SSOLogin")
    @WebResult(name = "SSOLoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SSOLogin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SSOLogin")
    @ResponseWrapper(localName = "SSOLoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SSOLoginResponse")
    public String ssoLogin(
        @WebParam(name = "Guid", targetNamespace = "http://tempuri.org/")
        String guid);

}
