
package org.tempuri.user;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ADXMLService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.16.67.8/ADXML/ADXMLService.asmx?wsdl")
public class ADXMLService
    extends Service
{

    private final static URL ADXMLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADXMLSERVICE_EXCEPTION;
    private final static QName ADXMLSERVICE_QNAME = new QName("http://tempuri.org/", "ADXMLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.67.8/ADXML/ADXMLService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADXMLSERVICE_WSDL_LOCATION = url;
        ADXMLSERVICE_EXCEPTION = e;
    }

    public ADXMLService() {
        super(__getWsdlLocation(), ADXMLSERVICE_QNAME);
    }

    public ADXMLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADXMLSERVICE_QNAME, features);
    }

    public ADXMLService(URL wsdlLocation) {
        super(wsdlLocation, ADXMLSERVICE_QNAME);
    }

    public ADXMLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADXMLSERVICE_QNAME, features);
    }

    public ADXMLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ADXMLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ADXMLServiceSoap
     */
    @WebEndpoint(name = "ADXMLServiceSoap")
    public ADXMLServiceSoap getADXMLServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ADXMLServiceSoap"), ADXMLServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ADXMLServiceSoap
     */
    @WebEndpoint(name = "ADXMLServiceSoap")
    public ADXMLServiceSoap getADXMLServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ADXMLServiceSoap"), ADXMLServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADXMLSERVICE_EXCEPTION!= null) {
            throw ADXMLSERVICE_EXCEPTION;
        }
        return ADXMLSERVICE_WSDL_LOCATION;
    }

}
