
package org.tempuri.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ADXMLServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ADXMLServiceSoap {


    /**
     * 
     * @param startTime
     * @param endTime
     * @param type
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetADXmlDoc", action = "http://tempuri.org/GetADXmlDoc")
    @WebResult(name = "GetADXmlDocResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetADXmlDoc", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetADXmlDoc")
    @ResponseWrapper(localName = "GetADXmlDocResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetADXmlDocResponse")
    public String getADXmlDoc(
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        int type,
        @WebParam(name = "startTime", targetNamespace = "http://tempuri.org/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://tempuri.org/")
        String endTime);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDeleteUserInfo", action = "http://tempuri.org/GetDeleteUserInfo")
    @WebResult(name = "GetDeleteUserInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDeleteUserInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDeleteUserInfo")
    @ResponseWrapper(localName = "GetDeleteUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDeleteUserInfoResponse")
    public String getDeleteUserInfo();

    /**
     * 
     * @param sMessage
     * @param taskTitle
     */
    @WebMethod(operationName = "SendLogMessage", action = "http://tempuri.org/SendLogMessage")
    @RequestWrapper(localName = "SendLogMessage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendLogMessage")
    @ResponseWrapper(localName = "SendLogMessageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendLogMessageResponse")
    public void sendLogMessage(
        @WebParam(name = "sMessage", targetNamespace = "http://tempuri.org/")
        String sMessage,
        @WebParam(name = "TaskTitle", targetNamespace = "http://tempuri.org/")
        String taskTitle);

}
